name: pytest

on:
  pull_request:
    branches:
      - "*"

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest
